import "@/styles/global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const AuthLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="ja">
      <body className="bg-slate-300 h-screen w-screen flex justify-center items-center">
        <div className="text-center">
          <div className="mb-3">aa</div>
          {children}
        </div>
      </body>
    </html>
  );
};
export default AuthLayout;
